apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    {{ include "monitor.labels" . | nindent 4 }}
